{% set name = "onnx-ir" %}
{% set version = "0.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/ir-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d428fdc2189d16b4651b8ad01ee2c7cf0b450559d67fb5564683355e53bcb4d3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=70
  run:
    - python
    - numpy
    - onnx >=1.16
    - typing_extensions >=4.10
    - ml_dtypes >=0.5.0

# TODO: remove next time after onnxscript release:
# E   ModuleNotFoundError: No module named 'onnxscript'
{% set deselect_tests = "--deselect=tests/public_api_test.py::TestPublicApiNamespace::test_correct_module_names" %}

test:
  source_files:
    - tests
    - testdata
  imports:
    - onnx_ir
  requires:
    - pip
    - pytest !=7.1.0
    - parameterized
    - pytorch >=2.3
    - safetensors  # [py<314]
    - onnxruntime >=1.17.0  # [py<314]
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}

about:
  home: https://onnx.ai/ir-py
  summary: An in-memory IR that supports the full ONNX spec, designed for graph construction, analysis and transformation.
  description: An in-memory IR that supports the full ONNX spec, designed for graph construction, analysis and transformation.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://onnx.ai/ir-py
  dev_url: https://github.com/onnx/ir-py

extra:
  recipe-maintainers:
    - apmorton
